# Generated by Django 5.1 on 2024-09-02 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0003_cattegory_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.DeleteModel(
            name='Uploads',
        ),
        migrations.DeleteModel(
            name='Cattegory',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
