# Generated by Django 5.1 on 2024-09-03 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleryapp', '0004_remove_photo_category_delete_uploads_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='gallery_images/')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.DeleteModel(
            name='Animals',
        ),
        migrations.DeleteModel(
            name='Background',
        ),
        migrations.DeleteModel(
            name='Forest',
        ),
        migrations.DeleteModel(
            name='Landscape',
        ),
        migrations.DeleteModel(
            name='Nature',
        ),
        migrations.DeleteModel(
            name='Snow',
        ),
    ]
